name: dice_roller
description: An app for rolling dice

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/
    - assets/sounds/dice_roll_0.mp3
    - assets/sounds/dice_roll_1.mp3
    - assets/sounds/dice_roll_2.mp3
    - assets/sounds/dice_roll_3.mp3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/dice_alt.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
